### ISSUE TITLE
Running code without a Code Engine causes Scheduler to crash

### ISSUE THREAD

**Issue by marusshi** [karthikp-ubc/ThingsJS#25]
For example, if you use the ThingsJS CLI and do:
```
things-js run <file>
```
The program does not "belong" to any Code Engine instance and will cause an exception to be thrown from ```Scheduler.js:147``` because ```proc.engine``` does not exist:
```javascript
		Object.values(self.programs).forEach(function(proc){
			if (self.engines[proc.engine].status !== 'dead'){
				mapping[proc.engine].processes[proc.id] = {
```

**Comment by jungkumseok** [comment]
`things-js run` should be used only for local testing purposes and all normal code execution should be done through a `CodeEngine` instance. We will be documenting this point soon.

That said, I'll fix the `Scheduler` code to consider only processes that are running on top of a `CodeEngine`. After all, we cannot really schedule a process if we don't have information about where it is running. A process running without a `CodeEngine` should be considered as an external process even if it is launched using a `things-js` command.

I'll close this after I update the `Scheduler` code. Thanks!
