### ISSUE TITLE
GFS: appendFile() and deleteFile() have small bug related to query

### ISSUE THREAD

**Issue by marusshi** [karthikp-ubc/ThingsJS#33]
```appendFile()``` currently modifies no object because there is no query passed in to find the object.

Currently in ```lib/extensions/gfs/gfs.js:169```:
```javascript
				return FSObject.findOneAndUpdate(node._id, {  

```
It should be:
```javascript
				return FSObject.findOneAndUpdate( { _id: node._id }, {  

```

This is the same case for ```deleteFile()``` in ```lib/extensions/gfs/gfs.js:238```.

**Comment by xyzwwwww** [comment]
Fixed

**Comment by jungkumseok** [comment]
Btw, I removed `deleteFile` in ef9eee73afd6461040a17290a32a9a5a763049ed as there is no such function. Reference: https://nodejs.org/docs/latest-v8.x/api/fs.html

**Comment by xyzwwwww** [comment]
Yes but our GFS is currently not the exact map of fs. It was a
fucntionalities the GFS provides so a user can delete the file. Maybe just
keep it for now, but your choice.
