### ISSUE TITLE
File system: Need to organise the directory structure.

### ISSUE THREAD

**Issue by xyzwwwww** [karthikp-ubc/ThingsJS#35]
Creates the new file in the root directory. Needs organization

**Comment by xyzwwwww** [comment]
The writefile and readfile function only support for the operation in the root folder, once I want to specify a subdirectory like apps, it feels to navigate inside to do the read or write operation. For example
GFS.readFile('./code/test.json', function(err,data){
console.log(data);
})
should read te file inside the code folder, but it throw me an error as not found.
for write GFS.writeFile('./code/test.json', testdata,function(err,data){
console.log(data);
}), it failed to write data inside code folder and only write it to root folder.

**Comment by xyzwwwww** [comment]
The benchmarks are working fine as it is able to support read and write. The issue is with the Scheduler working.

**Comment by aliciatang07** [comment]
for the path direct issue, automation script need save the appjson file to apps folder so that scheduler can schedule running of the app

**Comment by xyzwwwww** [comment]
The tests run fine if the directory path is specified from what I see. The issue seems to be with nested folders Alicia.

**Comment by xyzwwwww** [comment]
The write function works but make sure that the file exists before you start writing it. When you are using gfs.writeFile(), the path that you pass, such as /apps/test.js , make sure test.js exists and then you will be able to write to the MongoDB.

**Comment by aliciatang07** [comment]
how can I make sure the file exist if I want to write a new file?
