### ISSUE TITLE
Global File system: path direct error in readfile and writefile function

### ISSUE THREAD

**Issue by aliciatang07** [karthikp-ubc/ThingsJS#40]
The writefile and readfile function only support for the operation in the root folder, once I want to specify a subdirectory like apps, it feels to navigate inside to do the read or write operation. For example
GFS.readFile('./code/test.json', function(err,data){
console.log(data);
})
should read te file inside the code folder, but it throw me an error as not found. 
for write GFS.writeFile('./code/test.json', testdata,function(err,data){
console.log(data);
}), it failed to write data inside code folder and only write it to root folder.

**Comment by xyzwwwww** [comment]
I am merging this issue with the previous one which was open.

**Comment by jungkumseok** [comment]
Currently you cannot use unix-style relative paths because what the cwd (current working directory) is for a ThingsJS worker is unclear. Once we establish what the cwd would be, we can start supporting relative paths. For now, let's just stick to absolute paths.

**Comment by xyzwwwww** [comment]
It is able to read from the folders. We tested. The problem currently is it
can only write to nested folders if there already exists a file. If the
file does not exist, it is unable to create the file in the nested folder.
So a separate create function should do the task?

Also second thing is will the users be running the benchmarks? The reason I
ask is for testing and running the benchmarks right now we have a small
hack that works but it might not work for the users.
