### ISSUE TITLE
test:scheduler: asynchronous mocha tests should use mocha's async API

### ISSUE THREAD

**Issue by jungkumseok** [karthikp-ubc/ThingsJS#45]
Many of the scheduler tests are failing and while I haven't looked closely enough to pin-point the cause of the failures, I see many "hacky" routines implemented just to handle asynchronous operations.

Mocha provides async support for code using Promise or callbacks thus:

```
// synchronous test
it('should test synchronously', function(){
        // test body
}

// asynchronous test (callback)
it('should test asynchronously', function(done){
        // test body
});

// asynchronous test (Promise)
it('should pass when Promise resolves', function(){
    return new Promise(function(resolve, reject){
        // test body
    });
});
```

There seems to be a few places where the test is using this API, but it should be used across all async tests and we shouldn't have to hack around it.

**Comment by marusshi** [comment]
I am using the third method (resolving the promise) for most async test cases. I just noticed that some of the code has been commented out in the ```dev``` branch that I believe is causing the tests to fail:

```
	// before(function(){
	// 	this.timeout(10000);

	// 	return new Promise(function(resolve){
	// 		self.server = mosca.Server({ port: 1883 });
	// 		self.server.on('ready', function(){
	// 			self.pubsub = new things.Pubsub('mqtt://localhost');
	// 			self.pubsub.on('ready', resolve);
	// 		});
	// 	});
	// });
```

I use the ```self.pubsub``` object to send application request to the Scheduler. 

I will make sure to review the code and modify anything that might be hacky however. Thanks!

**Comment by jungkumseok** [comment]
I see... can you try modifying that before block so it doesn't start a mosca server? run-all starts a mosca server at the beginning so trying to bind again to the same port causes error. The before block should just initialize the Pubsub client

**Comment by jungkumseok** [comment]
updated in 4d951b8abe5f74fa1abd5c51e36bfcdc272b0000
