### ISSUE TITLE
process.stdin.setRawMode does not work on Windows

### ISSUE THREAD

**Issue by marusshi** [karthikp-ubc/ThingsJS#6]
In _bin/things-js_, process.stdin.setRawMode is called to control running instrumented code through terminal input. This needs a TTY stream which is not provided by Windows and will throw the following exception:

>(node:9980) UnhandledPromiseRejectionWarning: TypeError: process.stdin.setRawMode is not a function

It might be a good idea to document that the CLI works best for Unix-like OS.

**Comment by jungkumseok** [comment]
Cool, do you think you can implement a solution and make a PR?
