### ISSUE TITLE
Check for valid instance is only done in Code.prototype.ipcSend()

### ISSUE THREAD

**Issue by marusshi** [karthikp-ubc/ThingsJS#7]
In **lib/core/Code.js**, _Code.prototype.pause()_, _Code.prototype.resume()_, and _Code.prototype.snapshot()_ all call _ipcSend()_ which checks that the instance_id passed in exists in the processes dict. However, _pause()_, _resume()_, and _snapshot()_ also rely on the instance_id being defined in the processes dict, and will throw an error from a bad instance_id leading to an undefined object - e.g.:
```
	if (instance.status === Code.Status.RUNNING){
	             ^

TypeError: Cannot read property 'status' of undefined
    at Code.pause (ThingsJS\lib\core\Code.js:678:15)
```

**Comment by jungkumseok** [comment]
Fixed in 9ced758c31943c6b4c88a558a829e942aceae583
