### ISSUE TITLE
Dispatcher.prototype.moveCode and Dispatcher.prototype.spawnCode missing arguments

### ISSUE THREAD

**Issue by marusshi** [karthikp-ubc/ThingsJS#8]
Dispatcher uses the function moveCode() and spawnCode() to make Code engine migrate/spawn code via pubsub. Code engine relies on the object _kwargs_ sent by the Dispatcher over pubsub to execute the command correctly. For migration/spawn, kwargs needs to have an instance_id.

However, Dispatcher does not provide this to Code engine, e.g.:
```
Dispatcher.prototype.moveCode = function(from_id, to_id, code_name){
	this.sendCommand(from_id, 'migrate_code', {
		engine: to_id,
		code_name: code_name
	})
};
```
Here, Dispatcher only provides kwargs with engine and code_name, causing errors when Code engine receives the command, e.g.:
> [ERROR] Code count.js ipcSend("undefined", "SNAPSHOT"): No child process

**Comment by jungkumseok** [comment]
Thanks for finding this! I'll fix it
